steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'ENV=dev'
      - '--tag'
      - 'eu.gcr.io/$PROJECT_ID/fasthtml-app:${SHORT_SHA}'
      - '--tag'
      - 'eu.gcr.io/$PROJECT_ID/fasthtml-app:latest'
      - '-f'
      - 'infrastructure/Dockerfile'
      - '.'
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/$PROJECT_ID/fasthtml-app:${SHORT_SHA}']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/$PROJECT_ID/fasthtml-app:latest']

timeout: 900s
